project_name: UNITE_deepfaek_classification
use_ckpt: true
ckpt_path: checkpoints
ckpt_monitor: MulticlassAveragePrecision
compile: true
wandb_watch: true
wandb_log_model: false
max_epoch: 20
acc_grad: 2
arch:
  num_cls: 2
  num_heads: 12
  num_frames: 32
  img_size: 384
encoder:
  model: google/siglip2-base-patch16-384
  use_auto_processor: true
datamodule:
  celeb_df_preprocess_path: celeb_preprocessed
  from_img: true
  val_split_ratio: 0.1
  use_gta_v: true
  gta_v_preprocess_path: gta_v_preprocessed
  gta_v_zip_path: mini-ref-sailvos.zip
  gta_v_down_path: gta_v
  gta_v_gdrive_id: 1-0Vu4X-pqb4Da226g1OALHytAlMRCC84
  do_preprocess: true
  loader:
    batch_size: 32
    num_workers: 8
    prefetch_factor: 1
    pin_memory: true
    persistent_workers: true
  dataset:
    video_decode_device: cpu
  sampler:
    real_weight: 0.4
    fake_weight: 0.35
    gta_weight: 0.25
    seed: null
    run_sample: 20000
lit_unite:
  unite_model:
    dropout: 0.1
    use_bfloat: true
  ad_loss:
    delta_within:
    - 0.01
    - -2.0
    delta_between: 0.5
    eta: 0.05
  optim:
    lr: 0.0001
    decay_steps: 1000
  loss:
    lambda_1: 0.5
    lambda_2: 0.5
augment:
  horizontal_flip: true
  rotation: false
  rotation_range: 10
  gaussian_blur: true
  gaussian_kernel:
  - 3
  - 7
  color_jitter: false
  color_jitter_brightness: 0.2
  color_jitter_contrast: 0.2
  jpeg: true
  jpeg_quality_range:
  - 60
  - 100
